name: Release package
on: 
  push:
    tags:
    - v*.*.*
    - '!v*.*.*-**'
jobs:
  package:
    name: package
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{matrix.nodeversion}}
        registry-url: https://registry.npmjs.org
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Unshallow clone for tags
      run: git fetch --prune --unshallow --tags
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Set package version
      run: npm version ${{env.RELEASE_VERSION}} --no-git-tag-version
    - name: NPM Install
      run: npm ci
    - name: build webpack
      run: npm run build
    - name: Copy package.json files
      run: cp package*.json ./dist
    - name: Copy README
      run: cp README.md ./dist
    - name: Compress SDK folder
      run: tar -zcf ./utils.tar.gz -C dist .
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: utils.tar.gz
        path: ${{ github.workspace}}/utils.tar.gz
    strategy:
      fail-fast: true
      matrix:
        nodeversion:
        - 14.x
  publish:
    name: publish package
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.nodeversion}}
          registry-url: https://registry.npmjs.org 
      - name: Download package
        uses: actions/download-artifact@v2
        with:
          name: utils.tar.gz
          path: ${{ github.workspace}}/
      - name: Unzip tar
        run: tar -zxf ${{github.workspace}}/utils.tar.gz
      - name: cat package.json
        run: cat package.json
    strategy:
      fail-fast: true
      matrix:
        nodeversion:
        - 14.x
    